### NumPy의 0차원 배열
- array() 함수에 1개의 값만 넣을 경우

In [5]:
import numpy as np

In [6]:
nums = np.array(3)
print(nums)
print(nums.ndim)
print(nums.shape)

3
0
()


In [7]:
nums = np.array([[1,4,2],[7,5,3]])
print(nums)
print(nums.ndim)
print(nums.shape)
print(len(nums.shape))
print(nums.size)

[[1 4 2]
 [7 5 3]]
2
(2, 3)
2
6


In [16]:
nums = np.array([[1,4,2], [7,5,3]])
print(nums[1, 1])
print(nums[1, :2])
print(nums[0:, 2:])
print(nums[0:, 0:2])

5
[7 5]
[[2]
 [3]]
[[1 4]
 [7 5]]


### Numpy 0차원 배열


In [18]:
nums = np.array(3)
print(nums)
print(nums.ndim)
print(nums.shape)

3
0
()


### NumPy의 3차원 배열

In [8]:
import numpy as np
nums = np.array([[[1,4,2], [7,5,3]],
                [[0,4,8],[6,9,1]],
                [[7,6,9],[4,0,8]]])
print(nums)


[[[1 4 2]
  [7 5 3]]

 [[0 4 8]
  [6 9 1]]

 [[7 6 9]
  [4 0 8]]]


### NumPy의 내장 함수를 사용한 배열 생성
- linspace(start, stop, num = ?, endpoint = ?, retstep = ?)
    - start부터 stop까지 num으로 지정된 요소의 수만큼 배열생성

In [9]:
import numpy as np
print(np.linspace(0,1,num=5,endpoint=True))
print(np.linspace(0,1,num=5,endpoint=False))
print(np.linspace(0,1,num=5,endpoint=False,retstep=True))

[0.   0.25 0.5  0.75 1.  ]
[0.  0.2 0.4 0.6 0.8]
(array([0. , 0.2, 0.4, 0.6, 0.8]), np.float64(0.2))


### NumPy 배열의 연결 
- vstack : 수직 방향 병합
- hstack : 수평 방향 병합

In [10]:
import numpy as np

x = np.array([9, 8, 7])
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.vstack([x, grid]))

[[9 8 7]
 [1 2 3]
 [4 5 6]]


In [11]:
import numpy as np

x = np.array([[9],
              [8]])
grid = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.hstack([x, grid]))

[[9 1 2 3]
 [8 4 5 6]]
